# config.yml

title: "&0Скупщик"

no-sell-message: "&6&lSELLER &8| &fУ вас недостаточно товара!"
sell-message: "&6&lSELLER &8| &f Вы получили &e{price} монет"

time-to-updates-1: 35 # в минутах
time-to-updates: 55 # в минутах

updates:
  slot: 4
  name: "&bВремя до обновления"
  lore:
    - "&e{time-1} "
    - "&e{time-2}"

close:
  material: BARRIER
  name: "&#FB0000Закрыть"
  lore:
    - "&7Нажмите, чтобы закрыть"

items:
  "10":
    material: GOLD_INGOT
    price: 45
    name: "&#00F4B6GOLD_INGOT"
    lore:
      - " "
      - "&7Предмет &8- &#0590DAЗолотой слиток"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "11":
    material: CHORUS_FLOWER
    price: 45
    name: "&#00F4B6CCHORUS_FLOWER"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAПлод хоруса"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "12":
    material: HAY_BLOCK
    price: 45
    name: "&#00F4B6HAY_BLOCK"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAБлок сена"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "13":
    material: PUMPKIN
    price: 45
    name: "&#00F4B6PUMPKIN"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAТыква"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "14":
    material: SHROOMLIGHT
    price: 45
    name: "&#00F4B6SHROOMLIGHT"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAГрибосвет"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "15":
    material: GLOWSTONE_DUST
    price: 45
    name: "&#00F4B6GLOWSTONE_DUST"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAСветокаменная пыль"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "16":
    material: WARPED_FUNGUS
    price: 45
    name: "&#00F4B6WARPED_FUNGUS"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAИскажённый гриб"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "19":
    material: SUGAR_CANE
    price: 45
    name: "&#00F4B6SUGAR_CANE"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAСахарный тросник"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "20":
    material: FERMENTED_SPIDER_EYE
    price: 45
    name: "&#00F4B6FERMENTED_SPIDER_EYE"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAПаучий маренованый глаз"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "21":
    material: COCOA_BEANS
    price: 45
    name: "&#00F4B6COCOA_BEANS"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAКакао бобы"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "22":
    material: WARPED_STEM
    price: 45
    name: "&#00F4B6WARPED_STEM"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAИскажённый стебель"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "23":
    material: CRIMSON_FUNGUS
    price: 45
    name: "&#00F4B6CRIMSON_FUNGUS"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAБагровый гриб"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "24":
    material: SWEET_BERRIES
    price: 45
    name: "&#00F4B6SWEET_BERRIES"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAСладкие ягоды"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "25":
    material: ENDER_PEARL
    price: 45
    name: "&#00F4B6ENDER_PEARL"
    lore:
      - " "
      - "&7Предмет &8- &#0590DAЭндер-жемчуг"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"

item-update:
  "10":
    material: PAPER
    price: 45
    name: "&#00F4B6PAPER"
    lore:
      - " "
      - "&7Предмет &8- &#0590DAБумага"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "11":
    material: NETHERITE_INGOT
    price: 45
    name: "&#00F4B6CNETHERITE_INGOT"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAНезеритовый слиток"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "12":
    material: BONE
    price: 45
    name: "&#00F4B6BONE"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAКость"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "13":
    material: STRING
    price: 45
    name: "&#00F4B6STRING"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAНить"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "14":
    material: TNT
    price: 45
    name: "&#00F4B6TNT"
    lore:
      - " "
      - "§7Предмет §8- &#0590DATNT"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
item-update-1:
  "10":
    material: BLAZE_ROD
    price: 45
    name: "&#00F4B6BLAZE_ROD"
    lore:
      - " "
      - "&7Предмет &8- &#0590DAОгненый стержынь"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "11":
    material: ANCIENT_DEBRIS
    price: 45
    name: "&#00F4B6CANCIENT_DEBRIS"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAДревний обломок"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "12":
    material: LEATHER
    price: 45
    name: "&#00F4B6LEATHER"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAКожа"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "13":
    material: FEATHER
    price: 45
    name: "&#00F4B6FEATHER"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAПеро"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"
  "14":
    material: IRON_INGOT
    price: 45
    name: "&#00F4B6IRON_INGOT"
    lore:
      - " "
      - "§7Предмет §8- &#0590DAЖилезный слиток"
      - " "
      - "&8 Стоимость"
      - "&7  Стоимость за 1 шт &8- §e45 монет"
      - "&7  Стоимость за стак &8- §e2,880 монет"
      - " "
      - "&7Повышеная цена &8- &e7,5 монет"
      - " "
      - "&#FFD139 Нажмите, чтобы продать"





